### PR TITLE
fix: `Chat.isMuted`

### LINKED ISSUE #2781: Bug: Chat.isMuted returns undefined
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am unable to check whether a chat is muted or not since `Chat.isMuted` always returns `undefined`

### Expected behavior

It should return boolean

### Steps to Reproduce the Bug or Issue

Execute the code

### Relevant Code

```js
const client = new Client();

client.on('qr', (qr) => {
  console.log('QR RECEIVED', qr);
});

client.on('ready', () => {
  const chat = (await client.getChats())[0]
  console.log('is chat muted', chat.isMuted); // returns undefined
});

client.initialize();
```

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Linux
Phone OS: Android
whatsapp-web.js version: 1.23.0
WhatsApp Web version: 2.2407.3
Node.js Version: v16.15.0

### Additional context

_No response_

### LINKED ISSUE #2800: Documentation - wrong method description
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Class: Chat
Method: sendSeen
Current description: 'Set the message as seen'

### Expected behavior

Expected description: 'Set the **chat** as seen'

Ideally it would clarify the mechanism: setting unreadCount to 0

### Steps to Reproduce the Bug or Issue

-

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

All

### Additional context

_No response_

### LINKED ISSUE #2801: Documentation - event not listed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Class: Client
Event 'remote_session_saved' not listed under **Events**

### Expected behavior

-

### Steps to Reproduce the Bug or Issue

-

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

All

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alechkos**
# PR Details

#### Changes:
1. `Chat.isMuted` property now shows valid value (and not `undefined`)
2. Each time the `Chat.mute` or `Chat.unmute` methods are called, the `isMuted` and `muteExpiration` properties of `Chat` instance are updated as expected
3. Methods `Chat.mute`, `Chat.unmute`, `Client.muteChat`, `Client.unmuteChat` now return
`Promise<{ isMuted: boolean, muteExpiration: number }>` instead of `Promise<void>`, for more clarity

## Related Issues

The PR closes #2781, closes #2800, closes #2801

## You can try the fix by running one of the following commands:

- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#fix-ismuted
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#fix-ismuted
```

## How Has The PR Been Tested

```js
// client initialization...

client.on('message', async (msg) => {
    const chat = await msg.getChat(); // chat is unmuted here
    console.log(chat.mute(new Date(2038, 0, 19, 3, 14, 7))); // expected output: { isMuted: true, muteExpiration: 2147476447 }
    console.log(chat.isMuted, chat.muteExpiration); // expected output: true 2147476447
    console.log(chat.unmute()); // expected output: { isMuted: false, muteExpiration: 0 }
    console.log(chat.isMuted, chat.muteExpiration); // expected output: false 0
});
```

## Types of Changes
- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix/feature that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project
- [ ] I have updated the usage example accordingly (example.js)
- [X] I have updated the documentation accordingly (index.d.ts)

### CODE REVIEW

**Comment by cabiamdos** [comment]
image
image
to me isn't working :/

**Review by shirser121 — APPROVED** [review]
LGTM

File: src/util/Injected/Utils.js [hunk 1]
```diff
@@ -457,7 +457,7 @@ exports.LoadUtils = () => {
         let res = chat.serialize();
         res.isGroup = false;
         res.formattedTitle = chat.formattedTitle;
-        res.isMuted = chat.muteExpiration == 0 ? false : true;
+        res.isMuted = chat.mute?.expiration !== 0;
```
Comment (tuyuribr) [inline src/util/Injected/Utils.js:460]: I have PTSD from this operator ahahha

**Review by tuyuribr — APPROVED** [review]
LGTM
