### PR TITLE
Fix method participant on sendMessage

### LINKED ISSUE #3779: Sending a message is not a function
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

 throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: window.Store.WidFactory.toUserWidOrThrow is not a function
    at window.WWebJS.sendMessage (pptr://__puppeteer_evaluation_script__:250:51)
    at async pptr://__puppeteer_evaluation_script__:10:25
    at ExecutionContext._ExecutionContext_evaluate (D:\Programação\Tek\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ExecutionContext.evaluate (D:\Programação\Tek\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
    at async Client.sendMessage (D:\Programação\Tek\node_modules\whatsapp-web.js\src\Client.js:1038:25)

### Expected Behavior

When I send a message to the bot, it stops

### Steps to Reproduce the Bug or Issue

 throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: window.Store.WidFactory.toUserWidOrThrow is not a function
    at window.WWebJS.sendMessage (pptr://__puppeteer_evaluation_script__:250:51)
    at async pptr://__puppeteer_evaluation_script__:10:25
    at ExecutionContext._ExecutionContext_evaluate (D:\Programação\Tek\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ExecutionContext.evaluate (D:\Programação\Tek\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
    at async Client.sendMessage (D:\Programação\Tek\node_modules\whatsapp-web.js\src\Client.js:1038:25)

### WhatsApp Account Type

WhatsApp Business

### Browser Type

Google Chrome

### Operation System Type

Windows

### Phone OS Type

Android

### WhatsApp-Web.js Version

1.33.2

### WhatsApp Web Version

1.33.2

### Node.js Version

22.15.0

### Authentication Strategy

LocalAuth

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by BenyFilho**
# PR Details

Fixing participant on the method sendMessage change window.Store.WidFactory.toUserWidOrThrow(from) to window.Store.WidFactory.asUserWidOrThrow(from)

## Description

Fixing participant on the method sendMessage change window.Store.WidFactory.toUserWidOrThrow(from) to window.Store.WidFactory.asUserWidOrThrow(from)

**It doesn't matter what operating system it is. If you are having trouble, review your steps.**

fixes #3779

## You can try the fix by running one of the following commands:

- NPM
`npm install github:BenyFilho/whatsapp-web.js#fix_participant_sendMessage`

- YARN
`yarn add github:BenyFilho/whatsapp-web.js#fix_participant_sendMessage`

## Motivation and Context

Some people are struggling with it. 

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).
- [ ] I have updated the usage example accordingly (example.js)

### CODE REVIEW

**Review by tuyuribr — APPROVED** [review]

File: src/util/Injected/Utils.js [hunk 1]
```diff
@@ -249,7 +249,7 @@ exports.LoadUtils = () => {
 
         if (typeof chat.id?.isGroup === 'function' && chat.id.isGroup()) {
             from = chat.groupMetadata && chat.groupMetadata.isLidAddressingMode ? lidUser : meUser;
-            participant = window.Store.WidFactory.toUserWidOrThrow(from);
+            participant = window.Store.WidFactory.toUserWidOrThrow(from) || window.Store.WidFactory.asUserWidOrThrow(from) || from;
```
Comment (alechkos) [inline src/util/Injected/Utils.js]: Why this?
```js
|| from
```

Comment (BenyFilho) [reply src/util/Injected/Utils.js]: Just in case the method doesn't work

**Review by fernandomondo — APPROVED** [review]

**Review by alechkos — APPROVED** [review]
