### PR TITLE
Fix groupChat addParticipants

### LINKED ISSUE #3522: An unknown error occupied while adding a participant
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

When trying adding users to join group return 
```
{
  '6010xxxxxx@c.us': {
    code: 400,
    message: 'An unknown error occupied while adding a participant',
    isInviteV4Sent: false
  }
}
```

### Expected Behavior

I expect to see 
```
{
'botNumber@c.us': {
  statusCode: 200,
  message: 'The participant was added successfully',
  isGroupCreator: true,
  isInviteV4Sent: false
}
```

### Steps to Reproduce the Bug or Issue

```js
whatsapp_client.on('ready', async () => {
    try {

        const groupId = '123456789@g.us';
        const chat = await whatsapp_client.getChatById(groupId);
        
        const numbers = ['60123456789'];

        var options = {
            autoSendInviteV4: true,
            comment: "Hello! Welcome to my group!",
            sleep: [500, 1000]
        }
        const participants = numbers.map(number => `${number}@c.us`);

        const result = await chat.addParticipants(participants, options );
        console.log('Result：', result);
    } catch (error) {
        console.error('Error：', error);
    }

});
```

### WhatsApp Account Type

Standard

### Browser Type

Chromium

### Operation System Type

Windows 11

### Phone OS Type

Android 11

### WhatsApp-Web.js Version

1.27.0

### WhatsApp Web Version

2.3000.1021852438

### Node.js Version

v22.14.0

### Authentication Strategy

LocalAuth

### Additional Context

I have tried reinstalling the library and logging in again, but it still doesn't work.

### LINKED ISSUE #3534: Got "Cannot read properties of undefined (reading 'toString')" when adding participant to a group
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

When I try to add a participant to any group, I get this message error. This happens in both standard and business whatsapp.

### Expected Behavior

Should bring me the expected return of the method

### Steps to Reproduce the Bug or Issue

```
var listNumbers = ['5519988014892@c.us']

client.on('qr', (qr) => {
  qrcode.generate(qr, { small: true });
});

client.on('message', async (msg) => {
  console.log(msg.body);
  if (msg.body === "ADD") {
    try {
      const chats = await client.getChats();
      const group = chats.find(chat =>
        chat.isGroup &&
        chat.name === 'Magic Monkei [ALPHA]'
      );

      if (!group) {
        console.log('Not found.');
        return;
      }

      if (group && group.isGroup) {
        listNumbers.forEach(async element => {
          const chatWithPerson = await client.getChatById(element);
          if (chatWithPerson) {
            const result = await group.addParticipants(chatWithPerson.id._serialized);
          }
        });
      }
    } catch (err) {
      console.error('Error', err);
    }
  }
});

client.initialize();
```

### WhatsApp Account Type

Standard

### Browser Type

Google Chrome

### Operation System Type

Windows

### Phone OS Type

Android

### WhatsApp-Web.js Version

1.27.0

### WhatsApp Web Version

2.3000.1022409608

### Node.js Version

22.13.0

### Authentication Strategy

LocalAuth

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by BenyFilho**
# PR Details

This PR fixed the groupChat.addParticipants, approveGroupMembershipRequests, and rejectGroupMembershipRequests

## Description

Fixing the groupChat.addParticipants, approveGroupMembershipRequests, and rejectGroupMembershipRequests methods.

## Related issues

fixes #3534
fixes #3522

## Motivation and Context

groupChat.addParticipants, approveGroupMembershipRequests, and rejectGroupMembershipRequests error: Cannot read properties of undefined (reading 'toString')

## How Has This Been Tested

```
// client initialization...

client.on('ready', async () => {
    const groupChat = await client.getChatById("xxxxxxxxxxxxxxxxx@g.us");
    await group.addParticipants(['xxxxxxxxxxxx@c.us']);
});
```

## You can try the fix by running one of the following commands:

- NPM
`npm install github:BenyFilho/whatsapp-web.js#fix-groupChat-addParticipants`

- YARN
`yarn add github:BenyFilho/whatsapp-web.js#fix-groupChat-addParticipants`

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).
- [ ] I have updated the usage example accordingly (example.js)

### CODE REVIEW

**Review by alechkos — APPROVED** [review]

**Review by alechkos — APPROVED** [review]

**Review by themazim — APPROVED** [review]

**Comment by themazim** [comment]
can confirm, works flawlessly.

File: src/structures/GroupChat.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ class GroupChat extends Chat {
                 419: 'The participant can\'t be added because the group is full'
             };
 
-            await window.Store.GroupQueryAndUpdate(groupWid);
+            await window.Store.GroupQueryAndUpdate({ id: groupId });
```
Comment (devlikepro) [inline src/structures/GroupChat.js:101]:
```suggestion
            await window.Store.GroupQueryAndUpdate({ id: groupWid._serialized });
```

File: src/util/Injected/Utils.js [hunk 2]
```diff
@@ -925,7 +925,7 @@ exports.LoadUtils = () => {
         let response;
         let result = [];
 
-        await window.Store.GroupQueryAndUpdate(groupWid);
+        await window.Store.GroupQueryAndUpdate({ id: groupId });
```
Comment (devlikepro) [inline src/util/Injected/Utils.js:928]:
```suggestion
        await window.Store.GroupQueryAndUpdate({ id: groupWid._serialized });
```

**Review by devlikepro — APPROVED** [review]
If we already have Wid - we can use it probably.
The fix works, TY! :tada:

**Review by tuyuribr — APPROVED** [review]

**Comment by medeirosnvk** [comment]
npm install github:BenyFilho/whatsapp-web.js#fix-groupChat-addParticipants

Este comando nao funciona.

npm ERR! code 1
npm ERR! The git reference could not be found
npm ERR! command git --no-replace-objects checkout fix-groupChat-addParticipants
npm ERR! error: pathspec 'fix-groupChat-addParticipants' did not match any file(s) known to git

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2025-06-20T16_11_45_723Z-debug-0.log

**Comment by BenyFilho** [comment]
> npm install github:BenyFilho/whatsapp-web.js#fix-groupChat-addParticipants
> 
> Este comando nao funciona.
> 
> npm ERR! code 1 npm ERR! The git reference could not be found npm ERR! command git --no-replace-objects checkout fix-groupChat-addParticipants npm ERR! error: pathspec 'fix-groupChat-addParticipants' did not match any file(s) known to git
> 
> npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2025-06-20T16_11_45_723Z-debug-0.log

This PR was merged because of that it was excluded. Update your lib:

https://github.com/pedroslopez/whatsapp-web.js/releases
