### PR TITLE
fix getInviteCode for group (#3007)

### LINKED ISSUE #3007: `getInviteCode` method is not working on 2.3000.xx
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My code has been working for a long time and then stopped working about 1 day ago.  I found that the getInviteCode() method for GroupChat is not working - even though the bot is an admin of the chat group (I know that this method should only be called if the bot is part of the chat group)``

### Expected behavior

I expected the invite code to be returned when this method is called.

### Steps to Reproduce the Bug or Issue

1. Get group chats that this bot belongs to
2. call getInviteCode of chats where bot is admin of group

### Relevant Code

    let chats = await client.getChats();
    chats = chats.filter(c => c.isGroup && !c.groupMetadata.isParentGroup && !c.groupMetadata.announce);
    for (const chat of chats) {
      // get participant info of this bot for this chat
      let pid = chat.participants.find(p => p.id._serialized == client.info.wid._serialized);
      if (pid.isAdmin) {
        // Only print invite code if bot is admin of this group
        let inviteCode = await chat.getInviteCode();
        console.log(`Invite code: ${inviteCode}`);
      }
    }

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Linux, Ubuntu 22.04.4 LTS
Node 20.11.1
WhatsApp Web version 2.3000.1013269842

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by themazim**
# PR Details

Fixes #3007 due to new method definition in 2.3xxxx. Now requires second parameter to be true (c)

Is compatible to 2.24xx
 
## Description

fix getGroupInvite by adapting 

## Related Issue

#3007 

## Motivation and Context

fix issue. 

## How Has This Been Tested

tested on Version 2.3000.1013455223 and 2.2413.51. Simply by requesting a  invite code and on both.

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

File: src/structures/GroupChat.js [hunk 1]
```diff
@@ -372,7 +372,12 @@ class GroupChat extends Chat {
     async revokeInvite() {
         const codeRes = await this.client.pupPage.evaluate(chatId => {
             const chatWid = window.Store.WidFactory.createWid(chatId);
-            return window.Store.GroupInvite.resetGroupInviteCode(chatWid);
+            
+            if(window.WWebJS.compareWwebVersions(window.Debug.VERSION, '>', '2.3000.0')){
+                return window.Store.GroupInvite.queryGroupInviteCode(chatWid, true); 
+            } else {
+                return window.Store.GroupInvite.queryGroupInviteCode(chatWid);  
+            }
```
Comment (alechkos) [inline src/structures/GroupChat.js:380]: @themazim 

Here changes were made inside `revokeInvite` method.
Please move them to `getInviteCode` method.

Comment (themazim) [reply src/structures/GroupChat.js]: thanks, more coffee I guess before creating PRs.

**Review by alechkos — APPROVED** [review]

**Comment by khsoh** [comment]
Thank you!  This fixed the problem.
