### PR TITLE
getProfilePicture Fix => Evaluation failed: Error: Comms::sendIq called before startComms

### LINKED ISSUE #1265: Error: Comms::sendIq called before startComms
### Bug description
When you call the function "getProfilePicUrl" "without multi device" I get an error and therefore I don't get a response image:

`Error: Evaluation failed: Error: Comms::sendIq called before startComms
     at N (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:6:118757)
     at R.i (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:6:117648)
     at Y (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:5:243670)
     at new y (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:5:236237)
     at https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:6:117623
     at Generator.next (<anonymous>)
     at t (https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:63784)
     at s (https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:63995)
     at https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:64054
     at Y (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:5:243670)
     at ExecutionContext._evaluateInternal (D:\Ampps\www\Trabajo\2019\Orkestra_Base\whatsapi\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:95:5)
     at async ExecutionContext.evaluate (D:\Ampps\www\Trabajo\2019\Orkestra_Base\whatsapi\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
     at async Client.getProfilePicUrl (D:\Ampps\www\Trabajo\2019\Orkestra_Base\whatsapi\node_modules\whatsapp-web.js\src\Client.js:879:28)`

but if I connect as a multi device the method "getProfilePicUrl" responds with the url of the image correctly

### LINKED ISSUE #1277: Error getting profile picture
### Bug description
When excute the function  getProfilePicUrl() it presents an error: 
**(node:32211) UnhandledPromiseRejectionWarning: Error: Evaluation failed: i**

### Reproduction steps
1. getContact()
2. with contact execute contact.getProfilePicUrl()

### Expected behavior 
String with profilePictureUrl is expected

### PR DESCRIPTION
**Pull request by jtouris**
Fix for getProfilePicture throwing error on non-MD devices:

Error: Evaluation failed: Error: Comms::sendIq called before startComms
at N (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:6:118757)
at R.i (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:6:117648)
at Y (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:5:243670)
at new y (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:5:236237)
at https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:6:117623
at Generator.next ()
at t (https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:63784)
at s (https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:63995)
at https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:64054
at Y (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:5:243670)

### CODE REVIEW

**Comment by jtourisNS** [comment]
Tested on MD & Non-MD devices & worked fine for me

**Review by jonaskirch — APPROVED** [review]
Its works.

File: src/Client.js [hunk 1]
```diff
@@ -876,11 +876,18 @@ class Client extends EventEmitter {
...
      */
     async getProfilePicUrl(contactId) {
-        const profilePic = await this.pupPage.evaluate((contactId) => {
+        const profilePic = await this.pupPage.evaluate(async contactId => {
             const chatWid = window.Store.WidFactory.createWid(contactId);
-            return window.Store.getProfilePicFull(chatWid);
+            let asyncPic = await window.Store.getProfilePicFull(chatWid).catch(() => {
+                return undefined;
+            });
+            if (!asyncPic) {
```
Comment (pedroslopez) [inline src/Client.js:884]: I think we should be explicit and only call the Wap function if we're not on MD. 

So, this would look something like:

```
if(window.Store.Features.features.MD_BACKEND) {
// use getProfilePicFull
} else {
// use Wap.profilePicFind
}
```

**Review by pedroslopez — CHANGES_REQUESTED** [review]
Nice! This seems to work, but we could avoid calling the Wap function unecessarily on MD and vice-versa by checking the feature status

File: src/Client.js (hunk 1 above)
Comment (jtourisNS) [reply src/Client.js:884]: Sounds good! I'll apply those changes & test again

**Review by lenivene — APPROVED** [review]
LGTM

**Review by devchopra999 — APPROVED** [review]

**Review by pedroslopez — APPROVED** [review]

**Review by purpshell — APPROVED** [review]
lgtm
