### PR TITLE
fix delete on 2.3000

### LINKED ISSUE #3047: Delete message with webpack-exodus
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Can't delete message in `github:pedroslopez/whatsapp-web.js#webpack-exodus`

### Expected behavior

Message deleted for everyone

### Steps to Reproduce the Bug or Issue

```ts
await message.delete(true);
```

### Relevant Code

_No response_

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

`github:pedroslopez/whatsapp-web.js#webpack-exodus`

### Additional context

Was working fine until 2 days ago

### PR DESCRIPTION
**Pull request by jrocha**
# PR Details

This is a fix for message delete on 2.3000.x

## Description

The expected object to delete a msg has changed. 

## Related Issue

https://github.com/pedroslopez/whatsapp-web.js/issues/3047

## How Has This Been Tested

Tested on my bot. seanesbo on Discord also agreed it works.
Did not test on < 2.3000.x

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

File: src/structures/Message.js [hunk 1]
```diff
@@ -510,7 +510,11 @@ class Message extends Base {
             
             const canRevoke = window.Store.MsgActionChecks.canSenderRevokeMsg(msg) || window.Store.MsgActionChecks.canAdminRevokeMsg(msg);
             if (everyone && canRevoke) {
-                return window.Store.Cmd.sendRevokeMsgs(chat, [msg], { clearMedia: true, type: msg.id.fromMe ? 'Sender' : 'Admin' });
+                if (window.WWebJS.compareWwebVersions(window.Debug.VERSION, '>', '2.3000.0')) {
```
Comment (alechkos) [inline src/structures/Message.js:513]:
```suggestion
                if (window.WWebJS.compareWwebVersions(window.Debug.VERSION, '>=', '2.3000.0')) {
```

New approach starts from v2.3000.0 inclusive

**Review by alechkos — CHANGES_REQUESTED** [review]

**Review by alechkos — APPROVED** [review]
