### PR TITLE
fix: `setDisplayName` changes name only locally

### LINKED ISSUE #3562: setDisplayName doesn't change profile name
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

I am trying to change my profile name

`await client.setDisplayName("New name")`

This function doesn't throw any errors, and profile name doesn't change 

### Expected Behavior

`await client.setDisplayName("New name")` to change the actual profile name

### Steps to Reproduce the Bug or Issue

1. ini client and process login
2. call `await client.setDisplayName("New name")`
3. Observe actual profile name - it hasn't been changed

### WhatsApp Account Type

Standard

### Browser Type

Chromium

### Operation System Type

Linux

### Phone OS Type

.

### WhatsApp-Web.js Version

1.26.1-alpha.3

### WhatsApp Web Version

1.26.1-alpha.3

### Node.js Version

18.20.7 OR 22

### Authentication Strategy

RemoteAuth

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alechkos**
# PR Details

## Description

The PR fixes an issue where the method [`Client.setDisplayName`](https://github.com/pedroslopez/whatsapp-web.js/blob/6e5325867df81f08be43638c895e88d27dbace59/src/Client.js#L1092) changes the user name only locally.

## Related Issue

Mentioned [here](https://github.com/pedroslopez/whatsapp-web.js/pull/2295#discussion_r1367815086).
After the #2816 was merged, the issue returned.

fixes #3562

## How Has This Been Tested

```js
// client initialization...

client.on('message', async (msg) => {
    if (message.body === '!setName test') {
        await client.setDisplayName(msg.body.split(' ')[1]); // now user name is 'test'
    }
});
```

## You can try the fix by running one of the following commands:
- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#set-display-name
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#set-display-name
```

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

File: src/Client.js [hunk 1]
```diff
@@ -1091,7 +1091,7 @@ class Client extends EventEmitter {
      */
     async setDisplayName(displayName) {
         const couldSet = await this.pupPage.evaluate(async displayName => {
-            if(!window.Store.Conn.canSetMyPushname()) return false;
+            if (!window.Store.Conn.canSetMyPushname()) return false;
```
Comment (tuyuribr) [inline src/Client.js:1094]: revert this

Comment (alechkos) [reply src/Client.js]: Done

**Review by tuyuribr — APPROVED** [review]

**Comment by Alna7ari** [comment]
this is also fix GroupChat methods, thanks

**Review by shirser121 — APPROVED** [review]
THANKS
