### PR TITLE
fix: correctly resolve media that hasn't been downloaded

### LINKED ISSUE #752: Download media past whatsapp web's cache limits
### Bug description
This morning when downloading old media in conversations, the following error occurred:

Evaluation failed: n
at ExecutionContext._evaluateInternal (/home/frank/apps/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async ExecutionContext.evaluate (/home/frank/apps/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
at async Message.downloadMedia (/home/frank/apps/node_modules/whatsapp-web.js/src/structures/Message.js:302:24)
at async /home/frank/apps/controllers/test.js:2697:17

### Reproduction steps
1. try downloading a message with old media using `downloadMedia()`

### Relevant code
` await message.downloadMedia().then((file)=>console.log(file))`

### Environment (please complete the following information):
**WhatsApp**
 - Account type [Standard / Business]: Business
 - Device OS [iOS / Android]: ANdroid
 - WhatsApp Web version [run `await client.getWWebVersion()`]:

**Library**
 - Browser [Chrome / Chromium]: chrome
 - NodeJS version (`node -v`): v14.14.0
 - npm or yarn version (`npm -v`): 6.14.10
 - whatsapp-web.js version: lasted
 
Structure messages
first not error // second error 

Screen Shot 2021-07-12 at 09 57 23

### PR DESCRIPTION
**Pull request by pedroslopez**
Looks like the function argument changed into an object in the latest update.

TODO: There still seems to be an issue with media that goes from INIT stage to REUPLOADING

### CODE REVIEW

File: src/structures/Message.js [hunk 1]
```diff
@@ -324,24 +324,28 @@ class Message extends Base {
...
+                    directPath: msg.directPath,
+                    encFilehash: msg.encFilehash,
+                    filehash: msg.filehash,
+                    mediaKey: msg.mediaKey,
+                    mediaKeyTimestamp: msg.mediaKeyTimestamp,
+                    type: msg.type,
+                    signal: (new AbortController).signal
+                });
+    
+                const data = window.WWebJS.arrayBufferToBase64(decryptedMedia);
```
Comment (kingIZZZY) [inline src/structures/Message.js:338]: need an additional catch for the occasion when this error happens:
```
(node:9076) UnhandledPromiseRejectionWarning: Error: Evaluation failed: DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at t.default (https://web.whatsapp.com/bootstrap_qr.e715964683fa904d24c6.js:19:117764)
    at t.default (https://web.whatsapp.com/bootstrap_qr.e715964683fa904d24c6.js:10:86971)
    at https://web.whatsapp.com/bootstrap_qr.e715964683fa904d24c6.js:10:85750
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.01f767f6389d1d9e6832.js:2:35021)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.01f767f6389d1d9e6832.js:2:35232)
    at q (https://web.whatsapp.com/bootstrap_qr.e715964683fa904d24c6.js:2:353990)
    at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.e715964683fa904d24c6.js:2:353571)
    at ExecutionContext._evaluateInternal (C:\dev\wtvr\whatsapp-export2\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\dev\wtvr\whatsapp-export2\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Message.downloadMedia (C:\dev\wtvr\whatsapp-export2\node_modules\whatsapp-web.js\src\structures\Message.js:311:24)
    at async Statement.<anonymous> (C:\dev\wtvr\whatsapp-export2\index.js:340:43)
```

**Comment by pedroslopez** [comment]
Merging this in to fix most cases, but still need to look into the `atob` error. I haven't seen that in my tests yet.
For now, we'll just return `null` for these cases.

**Comment by leftbrasil** [comment]
I'm sorry to comment on a old issue, but I'm having problems when i call downloadMedia() for gif and after some debug, found that mediaStage is 'FETCHING' causing the media to not download. When I REMOVED the check "msg.mediaData.mediaStage === 'FETCHING') ", the media downloaded correctly. On chrome devtools the mediaStage is "NEED_POKE" and also downloads correctly to base64. It's safe to remove the 'FETCHING' check from code?
