### PR TITLE
Handling client.logout() Exception gracefully with optional chaining  

### LINKED ISSUE #2442: client.logout() Exception
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When I use client.logout() with authStrategy: LocalAuth with specific dataPath and clientId. I get this error:
```
(node:12684) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'AppState')
    at __puppeteer_evaluation_script__:2:26
    at ExecutionContext._evaluateInternal (C:\Users\whataspp-transfer\whatsapp-web-use\software\whatsapp-web-software\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
versions:
```

### Expected behavior

The `logout` function should logout and not throw exception

### Steps to Reproduce the Bug or Issue

Use client.logout() with authStrategy: LocalAuth with specific dataPath and clientId.

whatsapp-web.js: 1.22.1
puppeteer: 21.1.0

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Windows 10

### PR DESCRIPTION
**Pull request by ayushmourya**
# PR Details

* Updated Client.js file logout function to handle incorrect data 
## Description
Added Optional Chaining to prevent code from breaking 

## Related Issue
closes #2442

## How Has This Been Tested

* Run the code locally to perform the same steps in issue, And no issue happend

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by Spoon-knif — APPROVED** [review]

**Comment by tuyuribr** [comment]
Not node 12 compliant #2389 (While we don't upgrade the node version we need to make sure the older versions work too )

**Comment by ayushmourya** [comment]
@tuyuribr  tuyuribr I have updated the code to handle all node versions

File: src/Client.js [hunk 1]
```diff
@@ -744,7 +744,9 @@ class Client extends EventEmitter {
      */
     async logout() {
         await this.pupPage.evaluate(() => {
-            return window.Store.AppState.logout();
+            if (window.Store && window.Store.AppState && typeof window.Store.AppState.logout === 'function') {
```
Comment (Adi1231234) [inline src/Client.js:747]: Now it is safe and won't throw exception, but what is the root cause of the problem, why ```window.Store.AppState``` is ```undefined```?

Comment (ayushmourya) [reply src/Client.js:747]: It's possible that the window.Store object or its AppState property is not fully initialized or defined at the time this code is executed. And if this code runs before the necessary initialization is complete, it can result in undefined variables.

**Review by Adi1231234 — APPROVED** [review]

File: src/Client.js (hunk 1 above)
Comment (Adi1231234) [reply src/Client.js:747]: OK I understand :)

**Review by Adi1231234 — APPROVED** [review]

**Comment by ayushmourya** [comment]
Hey @pedroslopez , Could you please review this PR, I believe it resolves the following issue https://github.com/pedroslopez/whatsapp-web.js/issues/2442

**Review by Adi1231234 — APPROVED** [review]

**Comment by Adi1231234** [comment]
Hey, how can we merge it? we just need approval?

**Review by Adi1231234 — APPROVED** [review]

**Comment by Adi1231234** [comment]
Hey, can someone review the PR please? @Spoon-knif @tuyuribr 
I think this bug is very important.
Thanks!

File: src/Client.js (hunk 1 above)
Comment (shirser121) [reply src/Client.js:805]: I dont think its should do nothing if the client already destroyed 
Maybe throw specific expectation that said the client already destroyed.
Because after that function the use will think the logout success

**Comment by Luskan777** [comment]
Hi,

Any news about this PR? I think it's very important.

Is it ready to be merged?

@tuyuribr , the fix seems to work now for old versions as you requested, could you approve the PR?

**Review by aliyss — APPROVED** [review]
lgtm

**Comment by catalinberta** [comment]
I would love to see more activity on this, as it is still an issue.
Still requires rebase + 2 more approvals.

**Review by pedro-severo — APPROVED** [review]

**Comment by pedro-severo** [comment]
The bug is still happening on the main branch : ( @tuyuribr and @shirser121, it is pending your approvals specifically, can you review and approve, if that is the case, please? : )

**Review by shirser121 — APPROVED** [review]
Thanks
