### PR TITLE
fix: send message properly

### LINKED ISSUE #3619: High CPU load after updating to v1.31.0
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

High CPU load after updating to version of 1.31.0
It was increased to 90-100% cpu

Image

### Expected Behavior

Low cpu usage

### Steps to Reproduce the Bug or Issue

Run project

### WhatsApp Account Type

Standard

### Browser Type

Chromium

### Operation System Type

Linux

### Phone OS Type

iOS

### WhatsApp-Web.js Version

1.31.0

### WhatsApp Web Version

1.31.0

### Node.js Version

18

### Authentication Strategy

LocalAuth

### Additional Context

_No response_

### LINKED ISSUE #3648: Message sent but no response displayed on WhatsApp Business
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

Message sent but no response displayed on WhatsApp Business

### Expected Behavior

Message sent but no response displayed on WhatsApp Business

### Steps to Reproduce the Bug or Issue

app.post('/send-message', [
  body('number').notEmpty(),
  body('message').notEmpty(),
], async (req, res) => {
  const errors = validationResult(req).formatWith(({
    msg
  }) => {
    return msg;
  });

  if (!errors.isEmpty()) {
    return res.status(422).json({
      status: false,
      message: errors.mapped()
    });
  }

  const number = phoneNumberFormatter(req.body.number);
  const message = req.body.message;

  const isRegisteredNumber = await checkRegisteredNumber(number);

Image

  client.sendMessage(number, message).then(response => {
    res.status(200).json({
      status: true,
      response: response
    });
  }).catch(err => {
    res.status(500).json({
      status: false,
      response: err
    });
  });
});

### WhatsApp Account Type

WhatsApp Business

### Browser Type

Chromium

### Operation System Type

Debian

### Phone OS Type

iOS

### WhatsApp-Web.js Version

latest

### WhatsApp Web Version

2.3000.1024708504

### Node.js Version

v16.18.1

### Authentication Strategy

LocalAuth

### Additional Context

Message sent but no response displayed on WhatsApp Business

### PR DESCRIPTION
**Pull request by alechkos**
# PR Details

## Description

`window.Store.SendMessage.addAndSendMsgToChat` returns an array of two Promises where the first one contains a sent message object and the second one contains the message send result object.
The properly use of that function is its destructuring and awaiting for the first Promise to be resolved.
If user wants to wait until the message is acknowledged by the server, they can use the `Client.sendMessage` with optional `waitMsgSent` property set to `true`:

```js
await client.sendMessage(chatId, 'test', { waitMsgSent: true };
```

We should not use the synchonization of the chat history each time the message is being sent, so the use of `window.Store.HistorySync.sendPeerDataOperationRequest` is incorrect and unnecessary in that context.

## Related Issue(s)

#3609, fixes #3648

## You can try the fix by running one of the following commands:
- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#fix-hight-cpu-consumption
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#fix-hight-cpu-consumption
```

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by shirser121** [comment]
we should use this:
```js
    const [msgPromise, sendPromise] = await await window.Store.SendMessage.addAndSendMsgToChat(chat, message);
```

In `addAndSendMsgToChat` there is a promise for msg and for ack 3 (success send)

File: src/util/Injected/Utils.js [hunk 1]
```diff
@@ -297,11 +297,9 @@ exports.LoadUtils = () => {
             return msg;
         }
 
-        await window.Store.SendMessage.addAndSendMsgToChat(chat, message);
-        await window.Store.HistorySync.sendPeerDataOperationRequest(3, {
-            chatId: chat.id
-        });
-        return window.Store.Msg.get(newMsgKey._serialized);
+        const [msg, _] = await window.Store.SendMessage.addAndSendMsgToChat(chat, message);
```
Comment (shirser121) [inline src/util/Injected/Utils.js]: What the msg const used for?
You already know the message id...

Comment (alechkos) [reply src/util/Injected/Utils.js]: @shirser121 
Corrected.

File: src/util/Injected/Utils.js [hunk 2]
```diff
@@ -297,10 +297,8 @@ exports.LoadUtils = () => {
             return msg;
         }
 
-        await window.Store.SendMessage.addAndSendMsgToChat(chat, message);
-        await window.Store.HistorySync.sendPeerDataOperationRequest(3, {
-            chatId: chat.id
-        });
+        await Promise.all(window.Store.SendMessage.addAndSendMsgToChat(chat, message));
```
Comment (shirser121) [inline src/util/Injected/Utils.js]: I don't sure this is what we want, are we want to force every sending wait and ack 1?
Sometimes its can take a long time

**Review by fernandomondo — APPROVED** [review]

File: src/util/Injected/Utils.js (hunk 2 above)
Comment (alechkos) [reply src/util/Injected/Utils.js]: @shirser121 
This is the same line you posted [here](https://github.com/pedroslopez/whatsapp-web.js/pull/3692#issuecomment-3162753182) just without using the results from function. We are waiting until the message is being really sent.

Comment (wis-dev) [reply src/util/Injected/Utils.js]: Hi, you are trying to wait the message response to obtain and return the id?
From my point of view and also for my use cases i don't need the id when I call the `sendMessage` method.
But maybe it's required, I do not have the entire context of the library.

**Comment by N0N4M3BNS** [comment]
The CPU is still the same on my side; it didn't show a difference before using your version and after using your version.

UPDATED:
I try to use it for multiple connections. After a few hours, the connection keeps disconnecting.

File: src/util/Injected/Utils.js (hunk 2 above)
Comment (alechkos) [reply src/util/Injected/Utils.js]: @wis-dev 
> Hi, you are trying to wait the message response to obtain and return the id?

No, I don't need the `id` since I already have it in [this](https://github.com/pedroslopez/whatsapp-web.js/blob/475224fc9f12158af038b603c84f611de6827fac/src/util/Injected/Utils.js#L255) line.
Here I'm waiting for the message being sent and the result being resolved, the first argument the array contains is the `msg` object, the second one is the resulting object `{ messageSendResult: 'OK', t: timestamp }`

**Comment by shirser121** [comment]
This is why i think we should set a flag that represent if you want until
the sending results or not

**Comment by alechkos** [comment]
@shirser121 
> [This is why i think we should set a flag that represent if you want until the sending results or not](https://github.com/pedroslopez/whatsapp-web.js/pull/3692#issuecomment-3172431946)

Something like this?

```js
window.WWebJS.sendMessage = async (chat, content, options = {}) => {
/* ... */

    const [msgPromise, sendMsgResultPromise] = window.Store.SendMessage.addAndSendMsgToChat(chat, message);
    await msgPromise;

    if (options.isSendMessageResultRequired) {
        await sendMsgResultPromise;
    }

/* ... */
};
```

**Comment by shirser121** [comment]
Yes, or `options.waitUntilMsgSent`

**Review by shirser121 — APPROVED** [review]
Perfect

**Comment by alechkos** [comment]
@tuyuribr Can you also review?

**Comment by voidpack** [comment]
i tested it work normally except for whatsapp bot with number got shadow ban. cannot send to new chat with no history chat to their c.us and lid number.  first send to c.us number failed ack convert to lid number still failed.

Faield sendMessage to xxxxxxxxxxx@c.us: Evaluation failed: Error: Lid is missin
g in chat table
    at new Error (<anonymous>:6:31)
    at i (https://static.whatsapp.net/rsrc.php/v4/yB/r/v6q6bKv8eOd.js:76:180)
    at Object.callback (https://static.whatsapp.net/rsrc.php/v4iln-4/yN/l/en_GB-
j/0alFfr6hIMm.js:742:1471)
    at Object.<anonymous> (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29Lhiy
YLE.js:231:7552)
    at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:67098
    at Array.map (<anonymous>)
    at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:66946
    at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:17483
    at jb (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:14343
)
    at ob (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:15012
)

only success when trigger ui open new chat and send to lid number.

i try search Object.keys(window.Store.SendMessage)); found 3 type
(3) ['addAndSendMsgToChat', 'resendMsgToChat', 'addMsgToChat']

**Comment by alechkos** [comment]
@voidpack
This happens when you try to send to the number with you have no chat history before?

**Comment by voidpack** [comment]
@alechkos right only send to number with no chat history. but it only occur on my whatsapps number which get shadow ban cannot directly sendMessage to new number with no chat history (i also try save that number to contact first but still failed sendMessage) always need trigger open new chat on ui web.

my other bot which didnt get shadow ban can sendMessage normally to number with no chat history.

**Comment by alechkos** [comment]
@voidpack 
Unfortunately there is not much to do with bans, you can try wrapping the `sendMessage` in trycatch block in the bot:

```js
try {
    await client.sendMessage(/*...*/);
} catch (error) {
    // open chat here
    await client.sendMessage(/*...*/);
}
```

**Comment by N0N4M3BNS** [comment]
@alechkos Yesterday I tested your branch; after that, I returned to the stable version. After returning to the stable version, my Chrome keeps crashing. I need to restart the connection to re-run Chrome. Something wrong with your branch?

**Review by tuyuribr — APPROVED** [review]

**Comment by seowzhenjun0126** [comment]
> i tested it work normally except for whatsapp bot with number got shadow ban. cannot send to new chat with no history chat to their c.us and lid number. first send to c.us number failed ack convert to lid number still failed.
> 
> Faield sendMessage to [xxxxxxxxxxx@c.us](mailto:xxxxxxxxxxx@c.us): Evaluation failed: Error: Lid is missin g in chat table at new Error (:6:31) at i (https://static.whatsapp.net/rsrc.php/v4/yB/r/v6q6bKv8eOd.js:76:180) at Object.callback (https://static.whatsapp.net/rsrc.php/v4iln-4/yN/l/en_GB- j/0alFfr6hIMm.js:742:1471) at Object. (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29Lhiy YLE.js:231:7552) at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:67098 at Array.map () at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:66946 at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:17483 at jb (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:14343 ) at ob (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:15012 )
> 
> only success when trigger ui open new chat and send to lid number.
> 
> i try search Object.keys(window.Store.SendMessage)); found 3 type (3) ['addAndSendMsgToChat', 'resendMsgToChat', 'addMsgToChat']

I am seeing this same error after using code from this branch. I am wondering is it just impacting some WhatsApp account, or will it eventually impact all WhatsApp accounts?

**Comment by robbchan** [comment]
> > i tested it work normally except for whatsapp bot with number got shadow ban. cannot send to new chat with no history chat to their c.us and lid number. first send to c.us number failed ack convert to lid number still failed.
> > Faield sendMessage to [xxxxxxxxxxx@c.us](mailto:xxxxxxxxxxx@c.us): Evaluation failed: Error: Lid is missin g in chat table at new Error (:6:31) at i (https://static.whatsapp.net/rsrc.php/v4/yB/r/v6q6bKv8eOd.js:76:180) at Object.callback (https://static.whatsapp.net/rsrc.php/v4iln-4/yN/l/en_GB- j/0alFfr6hIMm.js:742:1471) at Object. (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29Lhiy YLE.js:231:7552) at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:67098 at Array.map () at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:66946 at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:17483 at jb (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:14343 ) at ob (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:15012 )
> > only success when trigger ui open new chat and send to lid number.
> > i try search Object.keys(window.Store.SendMessage)); found 3 type (3) ['addAndSendMsgToChat', 'resendMsgToChat', 'addMsgToChat']
> 
> I am seeing this same error after using code from this branch. I am wondering is it just impacting some WhatsApp account, or will it eventually impact all WhatsApp accounts?

I'm facing this problem now. When i send message to a new xxx@c.us number. It can not send.

**Comment by robbchan** [comment]
https://github.com/wppconnect-team/wa-js/issues/2852#issuecomment-3179250528

> > i tested it work normally except for whatsapp bot with number got shadow ban. cannot send to new chat with no history chat to their c.us and lid number. first send to c.us number failed ack convert to lid number still failed.
> > Faield sendMessage to [xxxxxxxxxxx@c.us](mailto:xxxxxxxxxxx@c.us): Evaluation failed: Error: Lid is missin g in chat table at new Error (:6:31) at i (https://static.whatsapp.net/rsrc.php/v4/yB/r/v6q6bKv8eOd.js:76:180) at Object.callback (https://static.whatsapp.net/rsrc.php/v4iln-4/yN/l/en_GB- j/0alFfr6hIMm.js:742:1471) at Object. (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29Lhiy YLE.js:231:7552) at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:67098 at Array.map () at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:66946 at https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:17483 at jb (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:14343 ) at ob (https://static.whatsapp.net/rsrc.php/v4/ym/r/N_29LhiyYLE.js:231:15012 )
> > only success when trigger ui open new chat and send to lid number.
> > i try search Object.keys(window.Store.SendMessage)); found 3 type (3) ['addAndSendMsgToChat', 'resendMsgToChat', 'addMsgToChat']
> 
> I am seeing this same error after using code from this branch. I am wondering is it just impacting some WhatsApp account, or will it eventually impact all WhatsApp accounts?

Could releated to this: https://github.com/wppconnect-team/wa-js/issues/2852#issuecomment-3179250528
