### PR TITLE
fix: client.destroy() keeps trying to get QR code when client is not authorized yet.

### LINKED ISSUE #248: client.destroy() keeps trying to get QR code when client is not authorized yet.
### Bug description
Errors are being thrown when client is destroyed before authorizing with QR.

### Reproduction steps
1. client.initialize()
2. do not scan QR code
3. client.destroy()
...

### Expected behavior 
Client should stop the timer that keeps trying to get the QR code.

### Environment (please complete the following information):
**WhatsApp**
 - Account type [Standard / Business]: Standard
 - Device OS [iOS / Android]: Android
 - WhatsApp Web version [run `await client.getWWebVersion()`]: 2.20.140

**Library**
 - Browser [Chrome / Chromium]: Chromium
 - NodeJS version (`node -v`): 13.10.1
 - npm or yarn version (`npm -v`): 6.14.2
 - whatsapp-web.js version: 1.6.1

### PR DESCRIPTION
**Pull request by javierportillo**

### CODE REVIEW

File: src/Client.js [hunk 1]
```diff
@@ -118,11 +118,12 @@ class Client extends EventEmitter {
                 this.emit(Events.QR_RECEIVED, qr);
             };
             getQrCode();
-            let retryInterval = setInterval(getQrCode, this.options.qrRefreshIntervalMs);
+            this.retryInterval = setInterval(getQrCode, this.options.qrRefreshIntervalMs);
```
Comment (pedroslopez) [inline src/Client.js:121]: Looks good! One small thing I would change is make this variable more descriptive since it's now available on client. Please change this throughout the code :)

```suggestion
            this._qrRefreshInterval = setInterval(getQrCode, this.options.qrRefreshIntervalMs);
```

Comment (javierportillo) [reply src/Client.js]: Done

**Comment by pedroslopez** [comment]
LGTM!
