### PR TITLE
fix: Lid is missing in chat table

### LINKED ISSUE #3735: Lid is missing in chat table
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

Error: Evaluation failed: Error: Lid is missing in chat table
    at new Error (<anonymous>:6:31)
    at i (https://static.whatsapp.net/rsrc.php/v4/yj/r/d7JxpQJeMD7.js:77:180)
    at Object.callback (https://static.whatsapp.net/rsrc.php/v4iaUv4/y0/l/en_US-j/NtyF00PKfAp.js:736:1471)
    at Object.<anonymous> (https://static.whatsapp.net/rsrc.php/v4/yX/r/iY77ULDw0o9.js:230:7552)
    at https://static.whatsapp.net/rsrc.php/v4/yX/r/iY77ULDw0o9.js:230:67098
    at Array.map (<anonymous>)
    at https://static.whatsapp.net/rsrc.php/v4/yX/r/iY77ULDw0o9.js:230:66946
    at https://static.whatsapp.net/rsrc.php/v4/yX/r/iY77ULDw0o9.js:230:17483
    at jb (https://static.whatsapp.net/rsrc.php/v4/yX/r/iY77ULDw0o9.js:230:14343)
    at ob (https://static.whatsapp.net/rsrc.php/v4/yX/r/iY77ULDw0o9.js:230:15012)
    at ExecutionContext._ExecutionContext_evaluate (D:\f\lab\fa-jobs-ads\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (D:\f\lab\fa-jobs-ads\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
    at async Client.sendMessage (D:\f\lab\fa-jobs-ads\node_modules\whatsapp-web.js\src\Client.js:1038:25)

### Expected Behavior

It was working yesterday, today no matter what phone number I try, this error is thrown.

### Steps to Reproduce the Bug or Issue

```js
await client.sendMessage(peerId, media_file, {
                    sendSeen: true,
                    caption: m.caption,
                  });
```

### WhatsApp Account Type

Standard

### Browser Type

Google Chrome

### Operation System Type

Windows

### Phone OS Type

other

### WhatsApp-Web.js Version

1.33.0

### WhatsApp Web Version

0

### Node.js Version

0

### Authentication Strategy

LocalAuth

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by seowzhenjun0126**
# PR Details

Use `window.Store.FindOrCreateChat.findOrCreateLatestChat` to get chat. This should eliminate the `Lid is missing in chat table` error when calling the `sendMessage` method.

## Description

It seems like WhatsApp is moving towards Lid migration, and using `window.Store.Chat.get(chatWid)` does not register lid in the required location (though I'm not sure where `chat table` refers to).

## Related Issue(s)

fixes #3716, fixes #3735

## How Has This Been Tested
```
client.on('ready', async () => {
    await client.sendMessage('xxxxxxx@c.us', "Hello world!")
});

client.initialize();
```

## To apply the fix run one of the following commands:
- **NPM**
```powershell
npm i github:seowzhenjun0126/whatsapp-web.js#fix-lid-missing-in-chat-table
```
- **YARN**
```powershell
yarn add github:seowzhenjun0126/whatsapp-web.js#fix-lid-missing-in-chat-table
```

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by robbchan** [comment]
This pr could fix the issue where I send a message to a new xxx@c.us?

**Comment by seowzhenjun0126** [comment]
May I know what your issue is? This PR aims to fix an error that starts to show after https://github.com/pedroslopez/whatsapp-web.js/pull/3692 is merged into main branch.

**Comment by voidpack** [comment]
tested. worked like charm. now no need manual openchat from ui, can send to new number create chat

**Review by alechkos — COMMENTED** [review]
It’s preferred to first use synchronous functions like `window.Store.Chat.get`, and only if that returns `undefined`, switch to heavier asynchronous functions.

File: src/util/Injected/Utils.js [hunk 1]
```diff
@@ -548,7 +548,7 @@ exports.LoadUtils = () => {
                 chat = null;
             }
         } else {
-            chat = window.Store.Chat.get(chatWid) || (await window.Store.Chat.find(chatWid));
+            chat = (await window.Store.FindOrCreateChat.findOrCreateLatestChat(chatWid))?.chat || window.Store.Chat.get(chatWid) || (await window.Store.Chat.find(chatWid));
```
Comment (alechkos) [inline src/util/Injected/Utils.js]: What do you think about it?
First we are trying to get the chat from cache, and only if it is not there, to use more heavy functions like `find` and `findOrCreateLatestChat`.

```suggestion
            chat = window.Store.Chat.get(chatWid) || (await window.Store.Chat.find(chatWid)) || (await window.Store.FindOrCreateChat.findOrCreateLatestChat(chatWid))?.chat;
```

Comment (BenyFilho) [reply src/util/Injected/Utils.js]: I see your point, but in cases where that is the first contact, mainly using @lid method window.Store.FindOrCreateChat.findOrCreateLatestChat is preferable to send the message

Comment (alechkos) [reply src/util/Injected/Utils.js]: Makes sense. We should figure out when it is the first conversation.

Comment (voidpack) [reply src/util/Injected/Utils.js]: > I see your point, but in cases where that is the first contact, mainly using @lid method window.Store.FindOrCreateChat.findOrCreateLatestChat is preferable to send the message

edited:
sorry my bad.. 
first i only try delete chat after open the bot. it can send normal to new chat.
but after i retry testing with delete chat and reopen the bot.. it failed and still error lid is missing. so back to origin PR fix..

Comment (BenyFilho) [reply src/util/Injected/Utils.js]: Theoretically, it shouldn't be working that way, because getchat was working before, but not for the first message.
FindOrCreate could be the only one to get chats, because I think it searches for chats in cache, and if it doesn't find it, it creates a new one.

Comment (alechkos) [reply src/util/Injected/Utils.js]: If it doesn't find the chat in cache (the use of `window.Store.Chat.get`) then `window.Store.Chat.find` is called. But this won't resolve the issue with first chat as reported by some users.
But I tested to send to the user I have never chatted with, and it works fine.
But some users still can't do that and should use the `findOrCreateChat`.

Comment (alechkos) [inline src/util/Injected/Utils.js]:
```suggestion
            chat = window.Store.Chat.get(chatWid) || (await window.Store.FindOrCreateChat.findOrCreateLatestChat(chatWid))?.chat;
```

Comment (seowzhenjun0126) [reply src/util/Injected/Utils.js]: Let me test this out and get back to you.

Comment (seowzhenjun0126) [reply src/util/Injected/Utils.js]: The WA account that I work closely with got banned, so I'll have to wait for the account to be unbanned to try this out. I'll keep you posted.

Comment (stefanfuchs) [reply src/util/Injected/Utils.js]: I'm testing this branch with the suggestion above, and it's working well so far. 
I'll be observing for a couple of days if the service remains stable.

Comment (stefanfuchs) [reply src/util/Injected/Utils.js]: Seems to be working well after a couple of days.

Comment (alechkos) [reply src/util/Injected/Utils.js]: > [The WA account that I work closely with got banned, so I'll have to wait for the account to be unbanned to try this out. I'll keep you posted.](https://github.com/pedroslopez/whatsapp-web.js/pull/3703#discussion_r2280083151)

@seowzhenjun0126 did you get to try it out?

**Comment by RC047** [comment]
I've tried it and this time it doesn't work again :/

**Comment by ChrisJCastle93** [comment]
FYI This PR seems to resolve this issue I raised [here](https://github.com/pedroslopez/whatsapp-web.js/issues/3716)

File: src/util/Injected/Utils.js (hunk 1 above)
Comment (FernandoZueet) [reply src/util/Injected/Utils.js]: I've been testing it for a few days now and it's working correctly.

Comment (elhumbertoz) [reply src/util/Injected/Utils.js]: It is working fine.

**Review by elhumbertoz — APPROVED** [review]
It is working fine.

**Comment by tofers** [comment]
A couple of days ago, I updated the clients.  Some of them had problems sending “No LID for user.”

This problem was solved by searching for @lid at 1233123@c.us. 


I will continue to monitor the situation. So far, it is working. Either WA did something on their end.

**Comment by tofers** [comment]
I looked at the statistics for yesterday and today.

The error “No LID for user” occurred 12 times.

**Review by fernandomondo — APPROVED** [review]

**Review by BenyFilho — APPROVED** [review]

**Review by FernandoZueet — APPROVED** [review]

**Review by stefanfuchs — APPROVED** [review]

File: src/util/Injected/Utils.js (hunk 1 above)
Comment (seowzhenjun0126) [reply src/util/Injected/Utils.js]: > > [The WA account that I work closely with got banned, so I'll have to wait for the account to be unbanned to try this out. I'll keep you posted.](https://github.com/pedroslopez/whatsapp-web.js/pull/3703#discussion_r2280083151)
> 
> @seowzhenjun0126 did you get to try it out?

@alechkos  Sorry for the late update. I have just tested and on the account that was affected by this error, and this change still works fine.

**Comment by seowzhenjun0126** [comment]
> I looked at the statistics for yesterday and today.
> 
> The error “No LID for user” occurred 12 times.

@tofers  I have also faced this issue, and the fix for me was to add this code

```
if (!(await window.Store.QueryExist(chatWid))?.wid) {
    return null;
}
```

In this [window.WWebJS.getChat](https://github.com/pedroslopez/whatsapp-web.js/blob/main/src/util/Injected/Utils.js#L535) function after [this line](https://github.com/pedroslopez/whatsapp-web.js/blob/main/src/util/Injected/Utils.js#L537).

Can you try and see if it works for you?

File: src/util/Injected/Utils.js (hunk 1 above)
Comment (seowzhenjun0126) [reply src/util/Injected/Utils.js]: @alechkos Sorry I made a mistake. The function did complete without throwing any error, but the receiver never receive the message. I have just confirmed this with my user.

Switching back to the original proposed change makes it work again.

**Comment by tofers** [comment]
> Can you try and see if it works for you?

In fact, you are simply skipping the sending. 

I checked it and it works with  https://github.com/pedroslopez/whatsapp-web.js/pull/3702

1. Search for a link with "@lid"
2. Send a message

**Review by RC047 — APPROVED** [review]
the function is now fully working!

**Review by fernandomondo — APPROVED** [review]

**Comment by p30arena** [comment]
I confirm this fixes https://github.com/pedroslopez/whatsapp-web.js/issues/3735

**Comment by rogerwh** [comment]
I have this problem too, but it doesn't work if try the PR.
Should I have to do something else?

I have installed like this:

1. add this to package.json:  "whatsapp-web.js": "github:pedroslopez/whatsapp-web.js#pull/3703/head",
2. execute `npm install`

This show the new version of the repo, but it does not solve the problem, 

It coninues showing "Lid is missing in chat table" when trying to send a message

**Review by JuancaArg — APPROVED** [review]
To great. 100% work

**Comment by donlaser** [comment]
Works perfect!

i add this to my Dockerfile to patch  over 1.33.2


RUN sed -i "s/chat = window.Store.Chat.get(chatWid) || (await window.Store.Chat.find(chatWid));/chat = window.Store.Chat.get(chatWid) || (await window.Store.FindOrCreateChat.findOrCreateLatestChat(chatWid))?.chat;/g" /usr/src/app/node_modules/whatsapp-web.js/src/util/Injected/Utils.js


RUN sed -i "/window.Store.WAWebStreamModel = window.require('WAWebStreamModel');/a\\    window.Store.FindOrCreateChat = window.require('WAWebFindChatAction');" /usr/src/app/node_modules/whatsapp-web.js/src/util/Injected/Store.js

**Comment by abdullah230695** [comment]
https://github.com/pedroslopez/whatsapp-web.js/issues/3766

Is there a workaround to overcome this issue ?

**Comment by BenyFilho** [comment]
> #3766
> 
> Is there a workaround to overcome this issue ?

Just use this PR

**Comment by abdullah230695** [comment]
> > #3766
> > Is there a workaround to overcome this issue ?
> 
> Just use this PR

I have tried but it doesn't work for new message.

**Comment by alechkos** [comment]
https://github.com/pedroslopez/whatsapp-web.js/pull/3703/commits/043cec4ccbc8e9d91361b2cfdfb69c42741d70b4 maybe fixes #3716 and #3735. Have to be retested.

**Comment by momokang** [comment]
Tested it's working for me.

**Review by alechkos — APPROVED** [review]
I also tested the PR just now. The test case was sending a message to a contact with whom I had no prior conversation history.
The message was sent successfully to the `xxxxxxxxx@c.us` formatted number (not `@­lid`).
Additionally, no `Lid is missing in chat table` error was thrown.

**Review by tuyuribr — APPROVED** [review]
