### PR TITLE
fix: `delete` function for messages

### LINKED ISSUE #3245: message.delete() is not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am able to do all other actions successfully but message.delete() is not reflecting anything while it is not even throwing it. It is even able to find the same message when I re-run the script.

### Expected behavior

Delete the actual message (for me)

### Steps to Reproduce the Bug or Issue

Run a simple snippet, scan qr code and all. Now send the 'TEST MESSAGE' text to your phone. It won't get deleted on the phone or other whatsapp web. 
Also applies when I do the same deletion with message after searchMessages or chat.fetchMessages.

### Relevant Code

Some simple code to test this:
```js
client.on('message_create', async (message) => {
    try {
        if (message.body === 'TEST MESSAGE') {
            await message.delete();
            await message.reply('Thanks for message, let me come back soon');
        }
    } catch (error) {
        console.error('An error occurred:', error);
    }
});
```

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Mac
iOS
^1.25.0
2.3000.1015762919
v22.6.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alechkos**
# PR Details

Fix for the `Message.delete` function.

## Description

The PR fixes an issue where the [`delete`](https://github.com/pedroslopez/whatsapp-web.js/blob/6e5325867df81f08be43638c895e88d27dbace59/src/structures/Message.js#L502) function does not delete messages.

Also was added a possibility to pass a second boolean value into the function for clearing media in the device (`true` by default).

## Related Issue

closes #3245

## How Has This Been Tested

```js
// client initialization...

client.on('message', async (message) => {
    const sender = 'XXXXXXXXXXX@c.us';
    if (message?.author === sender || message?.from === sender) {
        // delete for everyone: true, clear media in device: true (by default)
        await message.delete(true);
        // delete for everyone: true, clear media in device: false
        await message.delete(true, false);
        // delete for everyone: false, clear media in device: true (by default)
        await message.delete(false);
        // delete for everyone: false, clear media in device: false
        await message.delete(false, false);
    }
});
```

Everything works as expected.

## You can try the fix by running one of the following commands:
- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#fix-delete-msg
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#fix-delete-msg
```

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

File: src/structures/Message.js [hunk 1]
```diff
@@ -498,23 +498,26 @@ class Message extends Base {
     /**
      * Deletes a message from the chat
      * @param {?boolean} everyone If true and the message is sent by the current user or the user is an admin, will delete it for everyone in the chat.
+     * @param {?boolean} [clearMedia = true] If true, any associated media will also be deleted from a device.
      */
-    async delete(everyone) {
-        await this.client.pupPage.evaluate(async (msgId, everyone) => {
+    async delete(everyone, clearMedia = true) {
```
Comment (tuyuribr) [inline src/structures/Message.js:503]: Should ClearMedia be true by default? this will delete the file from the device ?

Comment (alechkos) [reply src/structures/Message.js:503]: Yes, `clearMedia` is `true` by default in WA 
internals, also it was `true` before this PR.
I just added a choice for the user.

**Review by tuyuribr — APPROVED** [review]

**Review by tuyuribr — APPROVED** [review]

**Comment by hveiras** [comment]
Tested in my fork, seems to be working fine so far

**Comment by ky-zo** [comment]
Hi, any progress here? :)

**Comment by ms6rb** [comment]
I still have the same problem

**Comment by yandevv** [comment]
Any progress to this PR? I'm not being to delete any message by me to me (my own chat), both delete(true) and delete(false)...
Does this PR fix that too?

**Comment by alechkos** [comment]
@yandevv 

:(

**Review by shirser121 — APPROVED** [review]
LGTM
