### PR TITLE
Use idempotent exposeFunctionIfAbsent (no reinject flag)

### LINKED ISSUE #3249: Getting remote session client is not Ready
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I set a remote session and it works perfectly, when I try to recover the session (frontend disconnect and reconnect again to receive messages), I try to access the socket to listen the messages but it doesn't works , this only fails when I try to recover a remote session.

### Expected behavior

when the user calls to recover whatsapp remote session should be ready to listen messages

### Steps to Reproduce the Bug or Issue

1.- Create remote session
2.- Save whatasapp session on Mongo
3.- Ensure whatsapp session is saved
4.- Recieved message
5.- restart backend
6.- try to recover session
7.- it fails and can't recover session

### Relevant Code

```js
const getWhatsappSession = async (socket: Socket, token: string) => {
    try {
        const tenantId = getTenantID(token);
        
		let client = WhatsAppSession.getClient(tenantId);

		if(!client) {
			const store = new MongoStore({ mongoose });

			const tempClient = new Client({
				puppeteer: {
					args: ['--no-sandbox', '--disable-setuid-sandbox'],
				},
				authStrategy: new RemoteAuth({
					store,
					backupSyncIntervalMs: 300000,
					clientId: tenantId,
				})
			});
			WhatsAppSession.addClientToList(tempClient, tenantId);
			client = tempClient;
		}

		console.log('client', client);

        client.on("ready", () => {
            console.log('Client is ready for tenant:', tenantId);
            socket.emit("ready", {
                tenantId, message: 'Client is ready'
            });
            socket.emit("sessionActive", { tenantId, message: "WhatsApp session is active" });
        });

        client.on('message', async (message) => {
				console.log('MESSAGE FRMOM', message);

                const mssg: Message = {
                    seening: false,
                    type: MessageType.USER,
                    metadata: {},
                    message: message.body,
                    date: dayjs().toDate(),
                    user: message.from || ''
                };

                socket.emit('WSSP_MESSAGE_RECIVED', mssg);
            
        });

        client.on('disconnected', (reason) => {
            console.log(`Client disconnected for tenant ${tenantId}:`, reason);
            // Puedes manejar la reconexión aquí si es necesario
            socket.emit('sessionDisconnected', { tenantId, message: 'WhatsApp session disconnected', reason });
        });

		client.on('auth_failure', msg => {
			console.error('Authentication failure:', msg);
			socket.emit('sessionError', { message: 'Authentication failure', error: msg });
		});
		
		client.on('change_state', state => {
			console.log('Client state changed:', state);
			socket.emit('sessionStateChange', { tenantId, state });
		});

        const data = await client.initialize();

		console.log('initilized', data)

    } catch (err: any) {
        console.error('Error initializing WhatsApp session:', err);
        socket.emit('sessionError', { message: 'Error initializing WhatsApp session', error: err?.message });
    }
};
```

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Mac OS
Phone: Android | iOS
whatsapp-web.js version: 1.25.0
Node.js Version : 22.0.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devlikepro**
# PR Details
- Add  `exposeFunctionIfAbsent` aka idempotent version of `exposeFunction`
- Use  `exposeFunctionIfAbsent`
- Remove `reinject` flag (it's not required anymore)

## Related Issue
closes #3249

## Motivation and Context

Time to time we're getting the error
```
Failed to add page binding with name onAddMessageEvent: window['onAddMessageEvent'] already exists!"
```

The PR add `exposeFunctionIfAbsent`, which is essentially idempotent version of `exposeFunction` 
Ideally it should be `upsertFunction`, but we don't want to require updating puppeteer for this fix.

Also it allows avoiding passing around `reinject` flag

## Types of changes

- [ ] Dependency change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by purpshell — APPROVED** [review]

**Review by AlejandroGs13 — APPROVED** [review]
With this solution also fix this issue [https://github.com/pedroslopez/whatsapp-web.js/issues/3249#issuecomment-2322203975](url)

**Comment by devlikepro** [comment]
Hi! Let me know if I need to update it on the latest changes, we've been using this code for a long time, pretty good soltuion and allows to avoid unnecessary checks like for `onQRChangedEvent` events

https://github.com/pedroslopez/whatsapp-web.js/blob/796a0a2367cf997a1f73a1de765a8e2787fb4125/src/Client.js#L145-L164

**Comment by alechkos** [comment]
@devlikepro Please update your branch

**Comment by devlikepro** [comment]
@alechkos done!

However, with that approach, we'll need to remember to call ` exposeFunctionIfAbsent(pupPage, ...)`  instead of `this.pupPage.exposeFunction(...)`
I thought about patching it, but don't like this approach too much. It's better to explicitly call it, especially since all calls are made this way; it makes it easier for newcomers to understand.

File: src/Client.js [hunk 1]
```diff
@@ -178,82 +173,79 @@ class Client extends EventEmitter {
...
+            this.authStrategy.afterAuthReady();
+        });
+        let lastPercent = null;
+        await exposeFunctionIfAbsent(this.pupPage, 'onOfflineProgressUpdateEvent', async (percent) => {
+            if (lastPercent !== percent) {
+                lastPercent = percent;
+                this.emit(Events.LOADING_SCREEN, percent, 'WhatsApp'); // Message is hardcoded as "WhatsApp" for now
+            }
+        });
         const logoutCatchInjected = await this.pupPage.evaluate(() => {
```
Comment (devlikepro) [inline src/Client.js:244]: we can remove "if" as well. Just let me know if you approve the PR and we're going this way, I'll do that :+1:

Comment (devlikepro) [reply src/Client.js]: done

**Review by alechkos — APPROVED** [review]
